### ISSUE TITLE
Todo Editing Improvements

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#187]
Checklist:
- [ ] Don't offer a context/project if already assigned to the todo.
- [ ] Hide context/project suggestions by clicking the edit area outside their box.
- [ ] Don't automatically add creation date.
- [ ] [Ctrl + click to quickly select multiple projects/contexts.](#issuecomment-876960673).
- [x] [Confirm on edit cancelling](#issuecomment-874424054).
---

- (Text option) Don't offer a context/project if already assigned to the todo.

- If sugestions are shown, you should hide suggestions (like pressing Esc) by clicking on a part of the edit box other than the suggestions box (or the text field). For example, the surrounding white. Clicking outside the whole edit box should close editing as usual.

-  (Text option) Don't automatically add creation date.

**Comment by 9z0** [comment]
Steps:
1. Click a todo.
2. Make some changes.
3. Click outside edit box.

Actual: editing is cancelled and no changes are saved.

Suggested: show a confirmation to avoid losing changes.

Reason: mistaken closure happens, especially that the save button is close to the edge.

**Comment by ransome1** [comment]
> Steps:
> 
> 1. Click a todo.
> 2. Make some changes.
> 3. Click outside edit box.
> 
> Actual: editing is cancelled and no changes are saved.
> 
> Suggested: show a confirmation to avoid losing changes.
> 
> Reason: mistaken closure happens, especially that the save button is close to the edge.

This one is added in the next version. The confirmation will only be shown if there has been an edit to the text field.

> (Text option) Don't automatically add creation date.
Can you explain why and what "Text option" means?

Also I would suggest that we should collect any requirement in the inital post by editing it. It is somehow confusing if requirements appear in following postsor in the middle of a discussion.

**Comment by 9z0** [comment]
> This one is added in the next version. The confirmation will only be shown if there has been an edit to the text field.

👍

> > (Text option) Don't automatically add creation date.

It means a setting in config file(s), but not in the UI (like here: #151) to keep the UI simple. Is there a clearer way to describe these?


> Also I would suggest that we collect any requirement in the inital post by editing it. It is somehow confusing if requirements appear in following postsor in the middle of a discussion.

No problem. I will keep a checklist in the top post for reference.

**Comment by ransome1** [comment]
> Steps:
> 
> 1. Click a todo.
> 2. Make some changes.
> 3. Click outside edit box.
> 
> Actual: editing is cancelled and no changes are saved.
> 
> Suggested: show a confirmation to avoid losing changes.
> 
> Reason: mistaken closure happens, especially that the save button is close to the edge.

This one is available in https://github.com/ransome1/sleek/releases/tag/v1.0.9-rc.1

**Comment by 9z0** [comment]
When a project/context popup is show, allow ctrl +click to select more than one project (similar to how you select multiple files in a file manager).

During that, always keep showing the list as-is until the user clicks away or clicks on a project without ctrl. For example, If I typed `+lor` to show only some projects, don't close the list or reset the filter after the ctrl+click. Keep the same filtered suggestions.

**Comment by 9z0** [comment]
Bug:
- Open edit box and make changes
- Click outside the box. The "cancel edits" confirmation appears.
- Click outside the confirmation message.

Expected:
- Nothing happens. You can only take action by clicking "Confirm" or "Cancel".

Actual:
- The message is dismissed with confirmation (The edits are lost).

**Comment by ransome1** [comment]
> Bug:
> 
> * Open edit box and make changes
> * Click outside the box. The "cancel edits" confirmation appears.
> * Click outside the confirmation message.
> 
> Expected:
> 
> * Nothing happens. You can only take action by clicking "Confirm" or "Cancel".
> 
> Actual:
> 
> * The message is dismissed with confirmation (The edits are lost).

This is added to the final 1.10.

**Comment by aleksfadini** [comment]
Would love to be able to select more than one task with shift or click. Adding a context or a project to multiple tasks is now a bit clunky.

**Comment by 9z0** [comment]
@aleksfadini 

The other topic (#56)  you commented on is the right one.

This issue is about the edit box that appears when you click a todo. :)

**Comment by aleksfadini** [comment]
Whoops. Sorry! Feel free to delete my comment here, I think it's confusing. Thanks again, Sleek is awesome!

My best,
Alessandro
